# Generated by Django 4.2.6 on 2023-10-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
