# Generated by Django 4.2.2 on 2023-10-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
